//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKHO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int Id { get; set; }
        public int IdHangHoa { get; set; }
        public int IdPhieuNhap { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
