//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKHO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int Id { get; set; }
        public int IdPhieuXuat { get; set; }
        public Nullable<System.DateTime> NgayInHoaDon { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string NguoiIn { get; set; }
    
        public virtual PhieuXuat PhieuXuat { get; set; }
    }
}
